### ISSUE TITLE
Snippets are not syncing.

### ISSUE THREAD

**Issue by carlosmgilp** [tahabasri/snippets#19]
I use two computers, one at home and one at the office, when modifying the snippets on one of the computers on the other computer they are not updated.
This is a mistake or I am doing something wrong.
Thanks.

**Comment by tahabasri** [comment]
Are you using latest version 1.1 + ?

**Comment by carlosmgilp** [comment]
Hello @tahabasri how are you.
Sorry for my delay in responding, but I had no internet.

I am currently using:
VSCode 1.55.2
Snippets 1.1.1

The problem is that I create new snippets in my house and when I get to the office, it does not update, the new snippets that it creates do not appear.

[2021-04-28 10:04:29.658] [settingssync] [info] Snippets: No changes found during synchronizing snippets.

I don't know if I'm doing something wrong.
If I have to configure something else?
If you could review that and report anything to me, I appreciate it.

**Comment by tahabasri** [comment]
Thanks for reaching back ! Currently, snippets won't sync with your VSCode settings, I mean the data won't sync, but the extension settings will. In order to sync your snippets, you should use a cloud client in your machine, change default snippets location to a folder picked up by that cloud client and use in your other machine.

**Comment by carlosmgilp** [comment]
Hello @tahabasri how are you.
I am new to VSCode and not doing that, I will look for a manual or something like that.
I don't know if you know of any tutorial?
If not, I hope you update the extension.
I hope it is soon, the synchronization.
Your extension is very good, the only thing missing is the synchronization and to give more options to organize the snippets.
Thank you.

**Comment by olivierverwoerd** [comment]
I think it would be great if there where an option to sync the snippets in the settings file.
Or maybe an option to use the .vscode folder to have snippits bind to a certain project.

I tried ${workspaceFolder}/.vscode/snippets.json as a location but I don't think that works (or i am doing it wrong).

**Comment by olivierverwoerd** [comment]
Hope this helps.

**Comment by scientistzjf** [comment]
是的，我赞同增加同步功能，这样就完美了。

**Comment by scientistzjf** [comment]
Yes, I'm in favor of adding synchronization, which is perfect.

**Comment by tahabasri** [comment]
@olivierverwoerd thank you a lot for the suggested changes ! I took some time to play with/check your changes, and I noticed that by applying the setting `snippets.useWorkspaceFolder`, we will force all projects to use snippets in `.vscode` folder. I'm thinking there is a better way of implementing this which will not cause any side effects :
- improve extension to check if there is `snippets.json` inside `.vscode`
- if there is one, use it as default snippets location for that particular workspace only.
- else, use common default snippets location (used in settings)
- all this will be triggered if `snippets.useWorkspaceFolder` is enabled in the settings.

I'd like your feedback regarding this. Thanks !

**Comment by olivierverwoerd** [comment]
Cool. ill check it tomorrow.

**Comment by olivierverwoerd** [comment]
I rechecked it's behavior:

At the moment it, it works if you specify the snippets location yourself and expects an `empty.json`

so if you put these lines in the workspace settings and make an empty `snippets.json` it works.
```
    "snippets.snippetsLocation": ".vscode/snippets.json",
    "snippets.useWorkspaceFolder": true
```
This has the advantage that you can specify if you want your snippets somewhere else.
But this does have the disadvantage of causing a confusing behavior with the snippets location. 

My proposal:
Ill just make it so if `useWorkspaceFolder `is enabled it just makes the `.vscode/snippets.json` is it doesn't exist and just uses that. To not make it work on all workspaces, you could just enable the `useWorkspaceFolder  `only in the workspace and not in the userspace. so ill update that in the setting description so it's clear.

What do you think?

**Comment by olivierverwoerd** [comment]
If you do not have workspace settings. It has the default behavior.
If you have it turned on but no file (`.vscode/snippets.json`) is there you'll be greeted with this.

![image](https://user-images.githubusercontent.com/22635990/119813945-28bc8400-beea-11eb-84fe-bf98716edde4.png)

#25

**Comment by tahabasri** [comment]
Merged PR, thanks @olivierverwoerd for your contribution !

I won't close this issue yet as sync is currently fixed only for developers (using versioning system e.g Git + new workspace settings). Other 'non-developer' users will still need this feature in a more standard fashion. I had some time playing with [VSCode sync feature](https://code.visualstudio.com/docs/editor/settings-sync) and I was obliged to use `globalState` instead of real file on system to save snippets. New changes will be radical and will require a significant bump in app version, thus, I'll try to introduce a new major version 2.0.0 which will get rid of files on system and use VSCode provided APIs.

All future features/changes are tracked in #29.

Note: I haven't adapted yet the upcoming version to use the new setting `snippets.useWorkspaceFolder`.
